import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import {useEffect}from 'react'
import NavbarSettings from '@/components/NavbarSettings'


export default function Home() {

  return (
    <>
      <Head>
        <title>UNDER MAINTENANCE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <header class="fondo">
          <h1>
          <nav>
            <ul>
            
              <li class="">
                  <a href="/">
                  <span class="icon_Title">
                  <ion-icon name="football"></ion-icon>
                          </span><span class="textNav">Football</span></a>
              </li>
              <li>
                  <a href="#">
                        <span class="icon_Title">
                        <ion-icon name="basketball"></ion-icon>
                        </span><span class="textNav">Basketball</span>
                    </a>
              </li>
              <li>
                  <a href="#">
                  <span class="icon_Title">
                  <ion-icon name="american-football"></ion-icon>
                          </span><span class="textNav">NFL</span></a>
              </li>
              <li>
                  <a href="#">
                        <span class="icon_Title">
                                    <ion-icon name="home">
                                    </ion-icon>
                        </span>
                        <span class="textNav">eSports</span>
                    </a>
              </li>
              
            </ul>

          </nav>

          <NavbarSettings />

          </h1>
        </header>

        <div>
          <br/><br/>
          <iframe src="/cogs.gif" class="giphy-embed" allowFullScreen></iframe><p></p>

        </div>

      </main>
      <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    </>
  )
}
